paths:
  src:
    path: "../src/"

    styles:
      all : "../src/assets/styles/**/*.styl"
      main: "../src/assets/styles/main.styl"
      path: "../src/assets/styles"

    sprites:
      images: 
        all: "../src/assets/images/sprite/*"
        path: "../src/assets/images/sprite/"
      style: "../src/assets/styles/common/"

    scripts:
      local:
        all: "../src/assets/scripts/local/**/*.coffee"
      vendor:
        all: "../src/assets/scripts/vendor/**/*.js"

    images: 
      all: "../src/assets/images/**/*.*"
      path: "../src/assets/images"

    templates:
      all: '../src/templates/**/*.jade'
      path: '../src/templates'
      blocks: 
        all: '../src/templates/blocks/**/*.jade'
        path: '../src/templates/blocks'
      pages: 
        all: '../src/templates/pages/**/*.jade'
        path: '../src/templates/pages'

  built:
    path: "../built/"

    styles:
      all: "../built/assets/styles/**/*.css"
      path: "../built/assets/styles"

    scripts:
      all: "../built/assets/scripts/**/*.js"
      path: "../built/assets/scripts/"
      local:
        path: "../built/assets/scripts/local"
      vendor:
        path: "../built/assets/scripts/vendor/"

    images: 
      all: "../built/assets/images/**/*.*"
      path: "../built/assets/images"
